apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: devuser
  namespace: openshift-storage
  labels:
    managed-by: gitops
spec:
  store: external-store
  displayName: "Dev User with 1GB Quota"
  quotas:
    maxSize: 1Gi
    maxObjects: -1
    maxBuckets: 10

